name: forcemvc
version: 0.0.2
author: Joris Hermans <hermansj@gmail.com>
description: A serverside mvc framework
homepage: https://github.com/jorishermans/dart-forcemvc
dependencies:
  unittest: '>=0.9.0 <0.9.1'
  http: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  route: '>=0.4.0 <0.5.0'
  uuid: '0.2.1'