name: forcemvc
version: 0.5.4
author: Joris Hermans <hermansj@gmail.com>
description: A serverside web mvc framework with templates
homepage: https://github.com/ForceUniverse/dart-forcemvc
dependencies:
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  route: '>=0.4.0 <0.5.0'
  mustache4dart: '>=1.0.0 <1.1.0'
  wired: '>=0.3.0 <0.4.0'
dev_dependencies:
  unittest: '>=0.11.0+2 <0.11.1'
  mock: '>=0.11.0 <0.11.1'

  
