name: forcemvc
version: 0.3.4+3
author: Joris Hermans <hermansj@gmail.com>
description: A serverside web mvc framework
homepage: https://github.com/jorishermans/dart-forcemvc
dependencies:
  http: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  route: '>=0.4.0 <0.5.0'
  mustache4dart: '>=1.0.0 <1.1.0'
  force_it: '>=0.1.3 <0.2.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.9.1'
  
