name: dartforcemvcexample
description: example of the dart force mvc framework
dependencies:
  forcemvc:
    path: ../../
  http: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.11.1'
